-   id: auto-smart-commit
    name: Auto Jira smart commit
    description: Automatically transform your Git commit messages into Jira smart commits
    entry: auto_smart_commit.py
    language: script
    stages: [prepare-commit-msg]
    always_run: true
